--DISPLAYING CONTENTS OF THE TABLE
SELECT * FROM Bangalore_1990_2022_BangaloreCity

--DISPLAYING UNIQUE YEAR DATA
SELECT DISTINCT YEAR(Date) FROM Bangalore_1990_2022_BangaloreCity ORDER BY YEAR(Date) 

--creating a new table with the average values for each year
CREATE TABLE AVG_TEMP_YEARLY_BLR
(YEAR INT PRIMARY KEY,
AVG_TEMP FLOAT,
MIN_TEMP_YEAR FLOAT,
MAX_TEMP_YEAR FLOAT,
AVG_PRECP FLOAT
)


--INSERTING VALUES INTO THE NEW TABLE
INSERT INTO AVG_TEMP_YEARLY_BLR
	SELECT YEAR(Date),AVG(tavg),MIN(tmin),MAX(tmax),AVG(prcp) FROM Bangalore_1990_2022_BangaloreCity
	GROUP BY YEAR(Date)
	
SELECT * FROM AVG_TEMP_YEARLY_BLR

--THE DATA IN MIN_TEMP_YEAR SEEMS TO BE INCORRECT. IT MIGHT BE DUE TO THE FACT THAT I REPLACED ALL THE ABSENT VALUES WITH ZERO.
--SO delete the table contents and UPDATE MIN and max COLUMN to avg values

TRUNCATE TABLE AVG_TEMP_YEARLY_BLR

INSERT INTO AVG_TEMP_YEARLY_BLR
	SELECT YEAR(Date),AVG(tavg),AVG(tmin),AVG(tmax),AVG(prcp) FROM Bangalore_1990_2022_BangaloreCity
	GROUP BY YEAR(Date)

SELECT * FROM AVG_TEMP_YEARLY_BLR



